# Generated by Django 5.2 on 2025-05-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='tanggal_kembali',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
