# Generated by Django 5.2 on 2025-05-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_peminjaman_tanggal_kembali'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='sudah_dikembalikan',
            field=models.BooleanField(default=False),
        ),
    ]
